"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const athlete = require("./athlete");
const classes_1 = require("./classes");
const constants = require("./consts");
let vm = new classes_1.vo2maxClass();
var ath = new athlete.athlete();
ath.name = 'Παναγιώτης Λυπηρίδης';
vm.bicycling = 23.1;
ath.vo2max = vm;
ath.vo2max.bicycling = 32;
console.log(`To όνομα είναι: ${ath.name}`);
console.log(constants.MINHEIGHT);
ath.weight = constants.MINWEIGHT + 1;
console.log(ath.weight);
