"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const athlete_1 = require("./src/athlete");
exports.athlete = athlete_1.default;
const vo2max_1 = require("./src/vo2max");
exports.vo2maxClass = vo2max_1.default;
const heartRate_1 = require("./src/heartRate");
exports.HeartRate = heartRate_1.default;
const altitude_1 = require("./src/altitude");
exports.Altitude = altitude_1.default;
const consts_1 = require("../consts");
exports.MINWEIGHT = consts_1.MINWEIGHT;
exports.MAXWEIGHT = consts_1.MAXWEIGHT;
exports.MINHEIGHT = consts_1.MINHEIGHT;
exports.MAXHEIGHT = consts_1.MAXHEIGHT;
exports.MAXVO2MAX = consts_1.MAXVO2MAX;
exports.MINHEARTRATE = consts_1.MINHEARTRATE;
exports.MAXHEARTRATE = consts_1.MAXHEARTRATE;
