"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const athlete_1 = require("./src/athlete");
exports.Athlete = athlete_1.default;
const vo2max_1 = require("./src/vo2max");
exports.Vo2maxClass = vo2max_1.default;
const heartRate_1 = require("./src/heartRate");
exports.HeartRate = heartRate_1.default;
const altitude_1 = require("./src/altitude");
exports.Altitude = altitude_1.default;
const activity_1 = require("./src/activity");
exports.Activity = activity_1.default;
const records_1 = require("./src/records");
exports.Record = records_1.default;
const timeInZones_1 = require("./src/timeInZones");
exports.TimeInZones = timeInZones_1.default;
const exoplismos_1 = require("./src/exoplismos");
exports.Exoplismos = exoplismos_1.default;
const lap_1 = require("./src/lap");
exports.Lap = lap_1.default;
const track_1 = require("./src/track");
exports.Track = track_1.default;
const enums_1 = require("../enums");
exports.activitiesTypes = enums_1.activitiesTypes;
const trackpoint_1 = require("./src/trackpoint");
exports.TrackPointClass = trackpoint_1.default;
const consts_1 = require("../consts");
exports.MINWEIGHT = consts_1.MINWEIGHT;
exports.MAXWEIGHT = consts_1.MAXWEIGHT;
exports.MINHEIGHT = consts_1.MINHEIGHT;
exports.MAXHEIGHT = consts_1.MAXHEIGHT;
exports.MAXVO2MAX = consts_1.MAXVO2MAX;
exports.MINHEARTRATE = consts_1.MINHEARTRATE;
exports.MAXHEARTRATE = consts_1.MAXHEARTRATE;
const geoPoint_1 = require("./src/geoPoint");
exports.geoPoint = geoPoint_1.default;
class dummy {
}
exports.dummy = dummy;
